# .gitlab-ci.yml
image: docker:20.10.16

services:
  - docker:20.10.16-dind

variables:
  DOCKER_IMAGE: your-dockerhub-username/react-app
  DOCKER_TAG: $CI_COMMIT_SHORT_SHA
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

stages:
  - test
  - build
  - push

before_script:
  - apk add --no-cache nodejs npm curl

# Test stage
test:
  stage: test
  script:
    - echo "Installing dependencies..."
    - npm install
    - echo "Running tests..."
    - npm test -- --watchAll=false --passWithNoTests
    - echo "Building application..."
    - npm run build
  artifacts:
    paths:
      - build/
    expire_in: 1 hour
  cache:
    paths:
      - node_modules/
  tags:
    - docker

# Build Docker image
build-docker:
  stage: build
  script:
    - echo "Building Docker image..."
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
    - echo "Docker image built successfully"
  needs:
    - test
  tags:
    - docker

# Push to Docker Hub
push-docker:
  stage: push
  script:
    - echo "Logging into Docker Hub..."
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - echo "Pushing image to Docker Hub..."
    - docker push $DOCKER_IMAGE:$DOCKER_TAG
    - echo "Tagging as latest..."
    - docker tag $DOCKER_IMAGE:$DOCKER_TAG $DOCKER_IMAGE:latest
    - docker push $DOCKER_IMAGE:latest
    - echo "Logging out from Docker Hub..."
    - docker logout
    - echo "Image pushed successfully: $DOCKER_IMAGE:$DOCKER_TAG"
  needs:
    - build-docker
  tags:
    - docker