image: docker:20.10.16

services:
  - docker:20.10.16-dind

variables:
  DOCKER_IMAGE: noorulla007/react-app
  DOCKER_TAG: $CI_COMMIT_SHORT_SHA
  DOCKER_TLS_CERTDIR: ""   # required for dind

stages:
  - build_push

build_and_push:
  stage: build_push
  script:
    - echo "Logging in to Docker Hub..."
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - echo "Building Docker image..."
    - docker build -t "$DOCKER_IMAGE:$DOCKER_TAG" .
    - echo "Pushing commit-tagged image..."
    - docker push "$DOCKER_IMAGE:$DOCKER_TAG"
    - echo "Tagging image as latest..."
    - docker tag "$DOCKER_IMAGE:$DOCKER_TAG" "$DOCKER_IMAGE:latest"
    - docker push "$DOCKER_IMAGE:latest"
    - docker logout
  tags:
    - pro  
